import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import {signIn, signOut, useSession}from "next-auth/react"

export default function Home() {
  const [info,setInfo]=useState('welcome to nextjs chi')
  const handleclick=()=>{
    const h1 =document.querySelector('.h1')
    h1.innerText=setInfo('whats up today man? hope u good?')

  }
  const {data:session,status,loading}=useSession()
  console.log({session,status,loading}) 
  // console.log(users)
 
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



        <nav className=' navbar bg-dark '>
          <div className="">
            <a href="">Testing App</a>
          </div>
          <div>
            <a className='me-2 text-decoration-none' href="">Home</a>
            {!session?(

<Link href={'/api/auth/signin'} passHref>
        <a onClick={()=>{
          signIn()
        }}>
            sign in
        </a>
</Link> 
            ):(

             <Link href={'/api/auth/signout'}>
            <a className='m-2' onClick={
              ()=>{
                signOut()
              }
            }>sign out</a>
            </Link> 
            )}


          </div>
        </nav>




      <h1 className='h1'>{info}</h1>
      <button
      onClick={handleclick} 
      className="btn btn-info">okay 😜 </button>
      <Link href={'/users'} passHref>
      <h1>users</h1>
      </Link>

      {/* user1 in built api */}
      <Link href={'/user1'} passHref>
      <span className='h1'>user1</span>
      </Link>
     
    </div>
  )
 
}

